1 find the sum of value in a matrix by creating matrix

In [8]:
arr = [
    [2, 5, 8],
    [1, 3, 6],
    [4, 7, 9]
]

total_sum = sum(sum(row) 
                for row in arr)

print(f"The sum of values in the matrix is: {total_sum}")

The sum of values in the matrix is: 45


In [3]:
import numpy as np 
a = np.array ([1,3,12,57,2,8])
print (a.max())
print (a.min())

57
1


In [10]:
arr = [
    [2, 5, 8],
    [1, 3, 6],
    [4, 7, 9]
]

total_* = *(*(row) 
                for row in arr)

print(f"The multipy of values in the matrix is: {total_*}")

SyntaxError: invalid syntax (2597844949.py, line 7)

In [13]:
a = [
    [2, 5, 8],
    [1, 3, 6],
    [4, 7, 9]
]

b = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
]
def multiply_matrices(a, b):
    result = [[sum(a * b for a, b in zip(row, col)) for col in zip(*b)] for row in a]
    return result
result_matrix = multiply_matrices(a, b)

for row in result_matrix:
    print(row)


[2, 5, 8]
[1, 3, 6]
[4, 7, 9]


In [14]:
import numpy as np 
a = np.random.random([2,2])
b = np.random.random([2,2])
print (a)
print (b)

[[0.26515316 0.82419779]
 [0.71062828 0.47639785]]
[[0.67609298 0.16511433]
 [0.4439243  0.46119732]]


In [20]:
import numpy as np 
a = np.array([[2,2],[3,5]])
print (a)

[[2 2]
 [3 5]]


In [ ]:
 import numpy as np 
a = np.random.random([2,2])
b = np.random.random([2,2])
print (a)
print (b)