In [5]:
import numpy 
a = numpy.array([2,1,"B","T","E",3,"C","S","E",1,0,0,4,6])
print(a)


['2' '1' 'B' 'T' 'E' '3' 'C' 'S' 'E' '1' '0' '0' '4' '6']


EXPERIMET 1
Working with numpy array

In [6]:
import numpy as np 
arr = np.array([[ 1, 2, 3],[ 4, 2, 5]]) 
print("Array is of type: ", type(arr)) 
print("No. of dimensions: ", arr.ndim)  
print("Shape of array: ", arr.shape) 
print("Size of array: ", arr.size) 
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [7]:
a = np.linspace(5,50,10)
print(a)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [33]:
b = np.zeros(10)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [34]:
c = np.ones(10)
print(c)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [45]:
print (a.ndim)


1


In [42]:
print(a.shape)

(10,)


In [43]:
print (a.size)

10


In [8]:
print(a.dtype)

float64


In [9]:
p = np.array ([["kushagra"],["dubey"]])
print(p)

[['kushagra']
 ['dubey']]
